### ISSUE TITLE
Client: Löschen von PHP-Mailer-Logs direkt ermöglichen.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/dsgvo#34]

**Comment by alexplusde** [comment]
Das wurde meines Wissens in REDAXO gelöst, oder @skerbis ? Wenn man Logs deaktiviert, bleiben dann dennoch alte Logs erhalten?

**Comment by skerbis** [comment]
Nur das Logging wird deaktiviert. Löschen ist nicht vorgesehen.

**Comment by alexplusde** [comment]
Das ist blöd. Ich seh das inzwischen trotzdem eher als Button beim PHPMailer als hier.

**Comment by skerbis** [comment]
Jupp
