### ISSUE TITLE
Wenn Domain Name geändert wird müssen alle Verbindungen angepasst werden.

### ISSUE THREAD

**Issue by Pixeldaniel** [FriendsOfREDAXO/dsgvo#38]
Stand jetzt, wenn der Name einer Domain geändert wird, sind alle Texte weg.

**Comment by joachimdoerr** [comment]
Das sollte anders laufen. Die Domain darf nicht geändert werden - man sollte lediglich die Domain duplizieren können. Die alte Domain + dazugehörige Daten sollten dann gelöscht werden können.

**Comment by alexplusde** [comment]
Ist das wirklich einfacher / zielführender?

Dann muss in der rex_form das Bearbeiten-Feld schreibgeschützt werden und in der rex_list-Domainübersicht duplizieren-Button eingefügt werden - bei dem aber vorher gefragt werden muss, wie der duplizierte Datensatz zu lauten hat.

**Comment by joachimdoerr** [comment]
Ich denke mal es ist sicherer? Aber man kann das so oder so machen mir ist es eigentlich egal, das addon ist ja dein Baby, dann einfach umbenennen und DB Aktion durchführen.

**Comment by alexplusde** [comment]
@gharlan wie bekomme ich denn nach erfolgreichem Absenden von rex_form mit, was vorher und nachher in einem Feld drin stand?
