### ISSUE TITLE
Client / Server: Änderungen pushen können, nicht pullen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/dsgvo#41]
Mein gewählter Ansatz hat einen Design-Fehler, nämlich, dass momentan sowohl die Standalone-Variante, als auch die R5-Variante des Clients selbst dafür verantwortlich ist, die Daten zu ziehen. z.B. via Cronjob.

Ziel wäre es, dass der Server jede Änderungen proaktiv mitteilt.

@joachimdoerr vlt. hast du da einen cleveren Ansatz.

**Comment by joachimdoerr** [comment]
Das wäre wohl nicht der beste weg hier müsste der Server ja aktiv jeden Instanz anpingen. Die Frag ist ob der server jede Instanz kennen muss. Ich denke das pullen ist tatsächlich das bessere Design.

**Comment by alexplusde** [comment]
Auch wenn dann eine Verzögerung zwischen der Änderung stattfindet?

Szenario: Ich ändere einen Text am Server oder baue einen Tracking-Code ein. Diese Änderung ist dann nicht live, sondern ggf. erst am nächsten Tag oder durch manuelles Pingen übernommen.

Im Prinzip ist diese Funktionalität schon vorgesehen. Aktuell muss man dazu den Client manuell anstoßen.

**Comment by alexplusde** [comment]
Ich habe jetzt einen Link in der Server-Ansicht eingebaut, der die entsprechende Installation zum Abruf der Texte triggert. Könnte man noch automatisieren, bin aber eher Fan davon, die Kontrolle zu behalten.
