### ISSUE TITLE
Client / Server: Muster-Datenschutztexte vorinstallieren

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/dsgvo#44]
Hierzu wurde bei erecht24 angefragt - alternativ anderen Dienstleister finden, dessen Texte man lizenzfrei, ggf. mit Quellhinweis, übernehmen darf.

**Comment by joachimdoerr** [comment]
Quellhinweis sollte ja kein problem sein.

**Comment by alexplusde** [comment]
Da das Addon unter MIT-Lizenz steht, weiß ich nicht, ob solche Texte dann automatisch auch unter dieser Lizenz stehen müssen?

**Comment by skerbis** [comment]
@alexplusde da sich die Texte aktuell immer noch "dramatisch" ändern würde ich Dir davon abraten. 
Es sollte nicht die Aufgabe des AddOns sein den Content zu liefern. Damit schießt Du Dir ins Bein.

**Comment by joachimdoerr** [comment]
Der Punkt ist nicht zu verachten! Das kann sicher zu unschönen Problemen führen.

**Comment by alexplusde** [comment]
Guter Einwand. Dann werde ich maximal drei Beispiel-Texte zur Veranschaulichung mitliefern, damit zumindest klar wird, wie die Datensätze angelegt werden sollen.

**Comment by skerbis** [comment]
Nette Blintexte ja. Keine Mustertexte bitte. Dann eher ne Linkliste zu Generatoren , das kann man ja machen.

**Comment by alexplusde** [comment]
Ja, gerne. Brauchbare Alternativen zu erecht24?

**Comment by skerbis** [comment]
https://www.activemind.de/datenschutz/datenschutzhinweis-generator/
https://dsgvo-muster-datenschutzerklaerung.dg-datenschutz.de/#loaded
https://www.anwalt.de/vorlage/muster-datenschutzerklaerung.php
https://www.ratgeberrecht.eu/leistungen/muster-datenschutzerklaerung.html#Generator

Empfehle jedoch immer einen Berater heranzuziehen.

**Comment by alexplusde** [comment]
Rechtlich habe ich keinen Anbieter gefunden, der sich dazu bereit erklärt und sich hier über einen Backlink freut.

Vielleicht @novinet-dsteffen ?

**Comment by alexplusde** [comment]
Scheinbar nicht.

**Comment by novinet-dsteffen** [comment]
Hallo @alexplusde , sorry, gerade erst gesehen. Nein, ich kann keine Texte beisteuern, da ich die Texte die ich habe für meine Kunden "bezahle" und sie daher nicht allgemeingültig rausgeben kann.

**Comment by novinet-dsteffen** [comment]
Und ehrlicherweise würde ich ganz massiv davon abraten. Dafür gibt es extra Anbieter, die teilweise juristisch abgesichert sind. Wenn du da jetzt im Addon Mustertexte reinlädst, kann es sehr schnell so wirken als ob du als Projektverantwortlicher Ahnung davon hättest und auch die Verantwortung dafür trägst.
Bin also bei @skerbis: Links zu Generatoren als "Empfehlung"
