### ISSUE TITLE
Client: Tracking-Code-Ausgabe um Multidomain erweitern

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/dsgvo#46]
Im Moment werden im Beispiel alle Tracking-Codes unabhängig der Domain ausgegeben.

**Comment by joachimdoerr** [comment]
Es müssten auch die Tracking-Codes pro Domain erfasst werden und auch der Datenschutz müsste pro Domain aufgebaut werden. Ggf. könnte man ein "master"- und einen "pro-domaine"-Mode einrichten.

**Comment by alexplusde** [comment]
Tracking-Codes pro Domain ist kein Problem. Dafür gibt es ja einen Datensatz pro Domain und Sprache. Nur der Muster-Code enthält den Hinweis noch nicht.

Für den Abruf vom Server ist das auch bereits gelöst - hier muss man dann als Client eben pro Domain einen Cronjob zum Abruf anlegen.
