### ISSUE TITLE
Sprachkeys mit Präfix

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/dsgvo#49]
Die meisten Sprachkeys haben bereits den Präfix `dsgvo_`, manche aber auch nicht:
https://github.com/FriendsOfREDAXO/dsgvo/blob/master/lang/de_de.lang#L4-L17

Das ist problematisch, da die Übersetzungen einen großen Pool bilden, wenn ein anderes Addon also auch `title` nutzt, wird das eine das andere überschreiben.

**Comment by alexplusde** [comment]
Danke. Ich habe das auch bei anderen Addons so entdeckt und es scheint wohl zufällig noch nirgends kollidiert zu sein. Ich korrigiere das

**Comment by gharlan** [comment]
Wenn man den Addonkey als Präfix nutzt (so wie du es ja größtenteils hast), kann man ihn bei der Nutzung weglassen, wenn man mit `$this->i18n()` arbeitet (da wo es geht).
Also aus `$this->i18n('title')` wird `rex_i18n::msg('dsgvo_title')`.
Gleiches gilt für `translate:title` innerhalb der package.yml.

**Comment by alexplusde** [comment]
@pixeldaniel fyi
