### ISSUE TITLE
Yrewrite Abhängigkeit 

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/dsgvo#50]
Lt https://github.com/FriendsOfREDAXO/dsgvo/blob/994a5955352cf7ed0023c8bb4837cfaa388bd2b4/lib/dsgvo-sync.cronjob.php#L69

Ist yrewrite notwendig. Sollte in der package.yml notiert sein

**Comment by alexplusde** [comment]
Die Abhängigkeit wurde an der Stelle noch nicht aufgelöst... Danke für den Hinweis.
