### ISSUE TITLE
Abhängigkeit zu markitup auflösen 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/dsgvo#55]

**Comment by alexplusde** [comment]
Für den Abruf gibt es einen Parameter `html`, bei dem Markitup vorab gerendert wird. Warum sollte man die Abhängigkeit grundsätzlich auflösen?

**Comment by skerbis** [comment]
Ich brauche markitup sonst nicht ;-)

**Comment by skerbis** [comment]
Bei erecht 24 erhält man HTML-Code. Da macht markitup keinen sinn.

**Comment by alexplusde** [comment]
Eine Auswahl, welcher Editor geladen wird, wäre eine Option?

**Comment by skerbis** [comment]
Oder ggf. Eine Möglichkeit diesen mit Angabe der Class und Attribute zu ändern

**Comment by alexplusde** [comment]
@skerbis kannst du mich da unterstützen? Die Lösung, die du kürzlich diskutiert hast - also Attribute einstellen wie bei sked/yform, seh ich auch als zielführend an.

Einzustellen beim Client, beim Server und in den entsprechenden forms das Attribut auslesen. Der API-Parameter "html", der die Texte durch markitup gerenderd bekommt, müsste erhalten bleiben, könnte aber standardmäßig alternative Parameter entgegen nehmen wie "raw", "plain", "strict", o.ä.

**Comment by skerbis** [comment]
👍

**Comment by alexplusde** [comment]
@skerbis nutzt du das Addon noch?

**Comment by skerbis** [comment]
Nein
