### ISSUE TITLE
PHP-Code wird ausgegeben anstatt der DSGVO

### ISSUE THREAD

**Issue by helpy** [FriendsOfREDAXO/dsgvo#58]
https://github.com/FriendsOfREDAXO/dsgvo/blob/23216d7f8ca129043526f6e25ad4fea7fc6b10d8/module/module_output.inc#L3

Das verursacht Probleme bei mir!
Es wird PHP-Code ausgegeben anstatt der DSGVO.

Sollte das nicht `<?php` anstat `<?` sein?
Zumindest behebt das bei mir das Problem.

**Comment by alexplusde** [comment]
Danke, für den Hinweis. Ja, das muss leider an mehreren Stellen korrigiert werden. 

Kannst du hierzu evtl. einen PR auf GitHub machen?

**Comment by alexplusde** [comment]
(Kommt allerdings auf die Serverkonfiguration an)

**Comment by helpy** [comment]
Stimmt! Kommt auf die Serverkonfiguration an.
Könnte ich bei meinem Webhosting sogar umstellen, habe ich aber noch nie gemacht.

**Comment by alexplusde** [comment]
PR wurde übernommen
