### ISSUE TITLE
Abstand unter "Text aus Vorlage kopieren"

### ISSUE THREAD

**Issue by schorschy** [FriendsOfREDAXO/dsgvo#60]
Abstand unter dem Button "Deutsche Texte aus Vorlage kopieren" einfügen. Siehe Screenshot:

![bildschirmfoto 2018-07-11 um 08 45 50](https://user-images.githubusercontent.com/20090597/42555082-63b7922e-84e7-11e8-98a9-73b35d2e9e8d.png)

Gerne auch mir das Issue zuordnen und sagen wie's geht.

**Comment by alexplusde** [comment]
Das Menü gehört ohnehin überarbeitet, die Vorschau bspw. eher nach oben und ein "Alle Domains anzeigen"/"Zurück"-Button evtl. auch.

**Comment by alexplusde** [comment]
Falls je eine umfassende Überarbeitung kommt, dann wird das mit berücksichtigt.
