### ISSUE TITLE
CSS-Styles: Doppelter Inline-Style-Tag

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/dsgvo#66]
Wenn ich das Cookie-Consent des AddOns verwende, dann wird der öffnende und schließende Style-Tag doppelt generiert und ist dann im ausgelieferten Quelltext auch doppelt drin:
```<style><style>```
```</style></style>```

Das wird daran liegen, dass in dem Textfeld zum Eintragen eigener Stylesheets ein umschließender "<style></style>" im Editor standardmäßig steht. Offenbar wird das aber vom Skript selbst generiert, sodass es halt sich in der Ausgabe eben verdoppelt.

Mögliche Lösung: Das voreingetragene CSS-Stylesheet anpassen und den umschließenden Script-Tag entfernen...!?

**Comment by alexplusde** [comment]
Genau, das habe ich zu einem sehr späten Zeitpunkt erst korrigiert: im Editor darf kein Style-Tag stehen. Hast du geupdatet oder neu installiert?

**Comment by dpf-dd** [comment]
Also ich hab das AddOn vor ca. 4 Wochen installiert, aber kam erst heute dazu das mal zu testen. Im Redaxo-Installer wird mir aber kein mögliches Update angezeigt...

**Comment by alexplusde** [comment]
Sollte erledigt sein
