### ISSUE TITLE
frisch installiert wirft kommen jede menge notices… fast auf jeder seite

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/dsgvo#67]

**Comment by alexplusde** [comment]
PHP7.2?

**Comment by alexplusde** [comment]
Uff... ich habe es mit 7.2 im Einsatz, bisher konnte ich das aber in keinem Projekt feststellen. Scheinbar sind Notices standardmäßig da unterdrückt. Kannst du exemplarisch mal ein paar reinkopieren? (Sind es countable-notices?)

**Comment by alexplusde** [comment]
Oha. Okay. Das sollte nicht sein. Da wurde aber auch schon in #43 berichtet, ich hatte dann nur nichts mehr dazu gehört.

**Comment by olien** [comment]
Hier gibt es noch eine:

![image](https://user-images.githubusercontent.com/330516/44447726-56fa3000-a5e9-11e8-96a7-ff32deec9dbf.png)

**Comment by alexplusde** [comment]
Ich komme da im Moment nicht dazu, frühestens Ende September. Bis dahin würde ich mich über Unterstützung freuen (oder einfach die notices ausblenden ;))

**Comment by alexplusde** [comment]
@olien wärst du bereit, wieder mit einzusteigen oder bleibst du bei IWCC?

**Comment by olien** [comment]
Selbst wenn ich iwcc nutze kann ich trotzdem hier mitdenken :-). Bin jetzt aber für 14 Tage offline!!!!!!
