### ISSUE TITLE
youtube replacer

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/dsgvo#68]
Idee als Feature: Replacer für youtube videos - eine Lösung, um YT zwar einzubetten, aber erst das Einverständnis zu holen. Wir haben das als "rexsocial" mal für Twitter/FB in R4 gemacht. 

Hier gibt es ein paar gute Inspirationen zum Thema IMHO 
https://github.com/trewknowledge/GDPR/issues/33

**Comment by alexplusde** [comment]
Ja, das wäre auch mein Wunsch für alle Drittanbieter-Dienste

**Comment by cukabeka** [comment]
Hier (ausgerechnet!) habe ich eine ganz akzeptable Lösung gefunden im Livebetrieb: http://bayern.de/
Und hier eine ganz gute technische Doku mit Plugin-Links https://github.com/trewknowledge/GDPR/issues/33 - vielleicht ist das eine gute Quelle, um das zu integrieren?

**Comment by alexplusde** [comment]
#53
