### ISSUE TITLE
Beispiel-Setups für die wichtigsten Services

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/dsgvo#69]
Evtl juristisch kritisch, müsste jedoch mit entsprechendem Disclaimer funktionieren, oder? 

Es wäre in jedem Fall endlos hilfreich, sich für häufige Services wie
- Google Fonts
- Youtube
- Facebook
- Twitter
- Analytics
- Matomo

vorkonfigurierte Settings/Texte ziehen zu können. Ggf als SQL-import? Oder einen Community-Server, den man bei "Cronjob zur Abfrage der Textbausteine / zentrale Verwaltung der Tracking-Codes" eintragen kann?

**Comment by alexplusde** [comment]
In Rücksprache mit anderen habe ich mich dazu entschlossen, sich sowas nicht ans Bein zu binden und auf den Aufruf für Text-Quellen haben sich quasi keine Leute gemeldet.

**Comment by alexplusde** [comment]
Inoffiziell würde das aber durchaus gehen und blind Text würde auch helfen

**Comment by webregie** [comment]
Ich sitze auch etwas unwissend davor. Wie sieht es denn nun aus, wo trägt man Analytics sinnvoll als Opt-In ein?

**Comment by alexplusde** [comment]
Ist sowieso dasselbe Thema wie in #44
