### ISSUE TITLE
Cookie Consent: Callback-Funktion

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/dsgvo#73]
Es wäre eine wünschenswerte Funktion, wenn man beim Cookie Consent eine Callback-Funktion triggern könnte (out of the box)...
```$fragment = new rex_fragment();
$fragment->setVar('class', 'edit', false);
$fragment->setVar('title', $this->i18n('dsgvo_consent_css_title'), false);
$fragment->setVar('body', $content, false);
$fragment->setVar('buttons', $buttons, false);
-----------------------------------------------------------
$fragment->setVar('callback', 'mein_funktionsaufruf');
-----------------------------------------------------------
$content = $fragment->parse('core/page/section.php');
echo $content;
```

Ich fände das total schick :)
Die Callback-Funktion selbst kann ja manuell hinzugefügt werden. Ich denke das ist Admin-Sache dafür zu sorgen, dass individuelle Funktionen eingebunden sind.

Vielen Dank und einen lieben Gruß - und ich hoffe der Ton passt diesmal? ;)
Stefan / dpf-dd

**Comment by alexplusde** [comment]
Klar, pr welcome!

**Comment by dpf-dd** [comment]
Erledigt... Bitte um Prüfung

**Comment by alexplusde** [comment]
#74
